uploads = []

[[generated]]
id = "kg7w_h--wHlZYkzHMNVPA"
uri = "file://artifacts/pulserpm-mobile/assets/images/icon.png"
type = "image"
title = "pulserpm app icon"

[[outputs]]
id = "H7CCUYlPOMQ7ikruU_tnl"
uri = "file://PulseRPM_MLNN_Blockchain_Code.pdf"
type = "pdf"
title = "PulseRPM — MLNN & Blockchain Code Reference"

[[outputs]]
id = "YBuXkndwYtYUEztXELaqJ"
uri = "file://PulseRPM_Full_Codebase.pdf"
type = "pdf"
title = "PulseRPM Full Codebase Reference"

[[outputs]]
id = "LkWTpou0xOCz5a9xgSfS3"
uri = "file://PulseRPM_Build_Prompt.pdf"
type = "pdf"
title = "PulseRPM — Complete Build Prompt & Technical Specification"

[[outputs]]
id = "dotCHu6Cv36Ml8A5MYZ1P"
uri = "file://PulseRPM_Mobile.tar.gz"
type = "unspecified"
title = "PulseRPM Mobile App — Source Code"

[[outputs]]
id = "O3dEDW6l5Ui2T2kiZWyUw"
uri = "file://PulseRPM_Workspace.tar.gz"
type = "unspecified"
title = "PulseRPM — Full Workspace Source Code"

[[outputs]]
id = "DBm0Db5e2yP7FphmW8KwT"
uri = "file://PulseRPM_API_Dashboard.tar.gz"
type = "unspecified"
title = "PulseRPM — API Server & Dashboard Source Code"

[[outputs]]
id = "iUGUbemt5898jYnDCFatV"
uri = "file://PulseRPM_api-client-react.tar.gz"
type = "unspecified"
title = "@workspace/api-client-react — package.json & library"
